### ISSUE TITLE
Error: Cannot find module [package]/collection/components/*/*.js

### ISSUE THREAD

**Issue by JohnCido** [petermikitsh/stencil-react#1]
### Problem:
Console log as bellow:
`(node:34048) UnhandledPromiseRejectionWarning: Error: Cannot find module '/[root]/node_modules/[package]/collection/components/[component]/[component].js'`
After some checks, the correct path should be:
/[root]/node_modules/[package]**/lib**/collection/components/[component]/[component].js
The `collection` entry in `package.json` seems to be correct.

### Enviroment:
- macOS 10.14.6
- Node 10.14.2
- NPM 6.11.2

**Comment by petermikitsh** [comment]
Hi John, thanks for the bug report!

Are you using Stencil 1? This project is unit tested against a Stencil 1 project: [`@anjuna/core`](https://unpkg.com/browse/@anjuna/core@1.0.0-rc.2/).

At least in Anjuna, the manifest is located at `collection/collection-manifest.json`. Based off your report, it sound like `stencil-react` was able to find the manifest. Within the manifest file, there is an `entries` array. `stencil-react` project assumes those entries are relative file paths-- relative to the manifest file.

E.g, the manifest entries array contains `components/alert/alert.js`; the full path to `alert.js` is `[package]/collection/components/alert/alert.js`. In the case of Anjuna, there is no "lib" folder. (`stencil-react` might need more projects to test against).

Can you confirm my assumptions here-- that the files in your manifest's `entries` array are relative paths, relative to the manifest file? Thanks.

**Comment by JohnCido** [comment]
1. The stencil entry in my devDependencies is `"@stencil/core": "^1.0.0"`.
2. I confirmed all entries in `collection-manifest.json` are in the format of `'components/*/*.js'`.

**Comment by JohnCido** [comment]
Since I'm working on a company project, I can only provide this simplified published package folder structure:
- lib
  - cjs
  - collection
    - components
      - [component]
        - [component].js
        - [component].css
    - shared
    - utils
    - collection-manifest.json
    - index.js
  - esm
  - [package_name]
  - loader
  - types
  - index.js
  - index.mjs
  - [package_name].js
- packages.json

**Comment by JohnCido** [comment]
I believe commit [64ac2e2](https://github.com/petermikitsh/stencil-react/commit/64ac2e2e4934e0e2f8ac203a029c4f663432e90e) has fixed this issue.
