### ISSUE TITLE
Feature Request: Customizable package.json output

### ISSUE THREAD

**Issue by JohnCido** [petermikitsh/stencil-react#2]
### Problem:
Unable to customize the final package.json output now.

**Comment by petermikitsh** [comment]
What fields of the package.json would you like to customize? Package name and version could be convenient. 

`main`, `module`, `types`, `peerDependencies`, and `dependencies` (https://github.com/petermikitsh/stencil-react/blob/master/src/index.js#L88-L96) should likely remain non-customizable.

**Comment by JohnCido** [comment]
It will be useful to let the user customize as many fields as they want, but exclude those you mentioned.

**Comment by petermikitsh** [comment]
I've thought about this, and I think the best option is a `--packageJson` CLI parameter, which is a JSON string that is spread into [the existing object](https://github.com/petermikitsh/stencil-react/blob/4fd2e14b3d7330417ae650ccba37f7c4d271f3f5/src/index.js#L81-L94).

**Comment by JohnCido** [comment]
Add this ability with pull request #5

**Comment by petermikitsh** [comment]
Closed via #5
