### ISSUE TITLE
Exported types in components are not included in the output

### ISSUE THREAD

**Issue by JohnCido** [petermikitsh/stencil-react#3]
### Problem:
I have a component like this:
```
...

export type IAction = {...}

@Component({...})
export class Bar extends ComponentInterface {
  @Prop() actions?: IAction[]
  ...
}
```
But in the generated binding component, the IAction is missing and causes an `unable to find IAction` error.
And because of this, the `button.d.ts` cannot be generated and causes an `Unable to find module './components/button/button'` error.

**Comment by petermikitsh** [comment]
Closing this with the recommendation that users switch to https://github.com/ionic-team/stencil-ds-plugins, which has full typescript support.
